### ISSUE TITLE
Move to the jupyterlab-contrib organization?

### ISSUE THREAD

**Issue by jtpio** [jupyterlab-contrib/jupyterlab-unfold#21]
This extension is great and as we were talking with @SylvainCorlay it might be a bit difficult to find.

How about moving it to the `jupyterlab-contrib` organization on GitHub? https://github.com/jupyterlab-contrib

One advantage of having it there is that it might be more visible. Also other folks might be more willing to contribute.

The process is to go to https://jupyterlab-contrib.github.io/ and click on "Transfer your extension":

![image](https://user-images.githubusercontent.com/591645/137005057-d2a182eb-9550-4816-8140-6260dfc03c51.png)

Thanks!

**Comment by martinRenou** [comment]
Done :)
