### ISSUE TITLE
Does not work with a custom drive

### ISSUE THREAD

**Issue by martinRenou** [jupyterlab-contrib/jupyterlab-unfold#33]
## Description

jupyterlab-unfold does not work with a custom drive, which might be one reason for which it does not work with the jupyterlab-github extension.

**Comment by kondratyevd** [comment]
Hi @martinRenou, I've stumbled upon this issue while trying to investigate why `jupyterlab-unfold` and `jupyterlab-github` extensions don't work together in my JupyterLab deployment.

I noticed that you mention this:
> which might be one reason for which it does not work with the jupyterlab-github extension

so I assume it was indeed a problem at some point. Do you know if the incompatibility was ever resolved?

Thanks!

**Comment by martinRenou** [comment]
It was resolved by #35. Could you open a separate issue with your case and specific packages versions?

**Comment by kondratyevd** [comment]
Thanks for the quick reply! I have created an issue: https://github.com/jupyterlab-contrib/jupyterlab-unfold/issues/40
