### ISSUE TITLE
Cannot change or drill into folders anymore?  

### ISSUE THREAD

**Issue by richlysakowski** [jupyterlab-contrib/jupyterlab-unfold#39]
The normal expected JupyterLab behavior of changing or drilling into a folder is gone.  

Double-clicking expands folders, but there is no way to make a folder and set the current working folder anymore.   We need this functionality back to drill into folder to set the current working folder.

**Comment by fcollonval** [comment]
@richlysakowski would you mind providing the versions you are using for JupyterLab and this extension?

**Comment by pdeffebach** [comment]
I just downloaded it today and ran into this problem. I'm on the latest version of Chrome, Ubuntu 22, and jupyterlab-unfold-0.2.2

Without a way to change directories in the file browser, I can't use this feature, unfortunately.

**Comment by Hoeze** [comment]
Same issue like mine, right?
https://github.com/jupyterlab-contrib/jupyterlab-unfold/issues/38
