### ISSUE TITLE
Incompatible with Jupyterlab 4.0.3 

### ISSUE THREAD

**Issue by LinuxIsCool** [jupyterlab-contrib/jupyterlab-unfold#42]
Running with 4.0.3 the file explorer interfaces is broken. No files shown, and no buttons work.

Switching to v3.60 of jupyterlab solved the issue.

**Comment by wyn-ying** [comment]
encountering the same issue

**Comment by martinRenou** [comment]
Thanks, this is now fixed in 0.3.0
