### ISSUE TITLE
Right click file/folder not possible since 0.3.1

### ISSUE THREAD

**Issue by Jeromekem** [jupyterlab-contrib/jupyterlab-unfold#52]
## Description

In jupyterlab-unfold version == 0.3.1, it is not possible to right click a single folder or file in an unfolded directory. This is the case for the latest Jupyterlab version, but also for older versions. Tested from (Jupyterlab version 4.1.5 and over).  It seems the handle is not pointing towards the correct location of the file or dir, only to the WORKDIR of jupyterlab. See screenshots:

![Screenshot 2024-05-28 at 17 18 29](https://github.com/jupyterlab-contrib/jupyterlab-unfold/assets/21338350/70994e90-7d43-40b7-bc55-efdf03f53770)
![Screenshot 2024-05-28 at 17 18 35](https://github.com/jupyterlab-contrib/jupyterlab-unfold/assets/21338350/2370044e-1a39-4c6a-a249-edfc77103b94)

As this eliminates the whole purpose of this unfold extension, I hope you can resolve it with this information:

## Reproduce

1. Unfold a directory
2. Right click on the child directory/file

## Expected behavior

When a directory is unfolded, one should be able to right click the file. This worked perfectly in jupyterlab-unfold version == 0.3.0. See screenshot: 
![Screenshot 2024-05-28 at 17 23 52](https://github.com/jupyterlab-contrib/jupyterlab-unfold/assets/21338350/d3ff0d8e-aba9-4236-9dbb-c701f063a9e3)

**Comment by martinRenou** [comment]
I just yanked the release 0.3.1 on PyPi, considering it broken.

We should keep this issue open though, to track the bug fix on master.

**Comment by michaelchia** [comment]
Sorry was caused by my PR. My bad.

**Comment by martinRenou** [comment]
No worries, thanks for looking into making a fix!

**Comment by Jeromekem** [comment]
Thanks @martinRenou @michaelchia . That was a quick ! Glad you were able to find the cause of the issue

**Comment by martinRenou** [comment]
0.3.2 is out!
