### ISSUE TITLE
jupyterlab-unfold make the shareable link not work.

### ISSUE THREAD

**Issue by specter119** [jupyterlab-contrib/jupyterlab-unfold#9]
jupyterlab version: 3.1.0 release in conda-forge
python version: 3.9.6 in conda-forge
jupyterlab-unfold version: 0.1.2 from pypi
platform: windows 10 pro.

After installing the jupyterlab-unfold, open the shareable link in the browser will not direct you to the exact notebook/folder as before. Disable the jupyterlab-unfold will make this function work again.

Besides, I fix the jupyterlab root dir in the config.

**Comment by martinRenou** [comment]
Thanks for reporting

**Comment by skbitsp** [comment]
https://github.com/jupyterlab-contrib/jupyterlab-unfold/pull/49 - this PR can be used to open shareable links provided the actual path in the link starts after `/tree/` (usually the paths are like: `http://localhost:8888/lab/workspaces/auto-Y/tree/first%20Folder/nb.ipynb`)
